# Generated by Django 3.1.5 on 2021-01-30 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image_Create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Clicked_by', models.CharField(max_length=50)),
                ('Uploaded_on', models.DateTimeField()),
                ('Image', models.ImageField(upload_to='images')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.category')),
            ],
        ),
    ]
